/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javagui.Display.DisplayClasses;
import javagui.Display.DisplayCourse_Credit;
import javagui.Display.DisplayCourses;
import javagui.Display.DisplayEnrollments;
import javagui.Display.DisplayGrades;
import javagui.Display.DisplayLogs;
import javagui.Display.DisplayPreReq;
import javagui.Display.DisplayStudents;
public class TableList extends javax.swing.JFrame {

    /**
     * Creates new form TableList
     */
    public TableList() {
        super("Fullscreen");
        getContentPane().setPreferredSize( Toolkit.getDefaultToolkit().getScreenSize());
        pack();
        setResizable(false);
        initComponents();
        this.getContentPane().setBackground(new Color(0,0,111));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        Course_Btn = new javax.swing.JButton();
        Classes_Btn = new javax.swing.JButton();
        CourseCredit_Btn = new javax.swing.JButton();
        Enrollments_Btn = new javax.swing.JButton();
        Grades_Btn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Course_Btn.setText("Courses");
        Course_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_BtnActionPerformed(evt);
            }
        });

        Classes_Btn.setText("Classes");
        Classes_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Classes_BtnActionPerformed(evt);
            }
        });

        CourseCredit_Btn.setText("Course Credit");
        CourseCredit_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseCredit_BtnActionPerformed(evt);
            }
        });

        Enrollments_Btn.setText("Enrollments");
        Enrollments_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enrollments_BtnActionPerformed(evt);
            }
        });

        Grades_Btn.setText("Grades");
        Grades_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grades_BtnActionPerformed(evt);
            }
        });

        jButton6.setText("Prerequisite");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Logs");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Display Tables");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CourseCredit_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Classes_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Course_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Enrollments_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Grades_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(130, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(Course_Btn)
                .addGap(18, 18, 18)
                .addComponent(Classes_Btn)
                .addGap(18, 18, 18)
                .addComponent(CourseCredit_Btn)
                .addGap(18, 18, 18)
                .addComponent(Enrollments_Btn)
                .addGap(18, 18, 18)
                .addComponent(Grades_Btn)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            //display students datatable
            DisplayStudents dis_st = new DisplayStudents();
            dis_st.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Course_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_BtnActionPerformed
        try {
            // TODO add your handling code here:
            
            //display course DataTable
            DisplayCourses dis_cr = new DisplayCourses();
            dis_cr.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Course_BtnActionPerformed

    private void Classes_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Classes_BtnActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            
            //display classes DataTable
            DisplayClasses dis_cls = new DisplayClasses();
            dis_cls.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Classes_BtnActionPerformed

    private void CourseCredit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseCredit_BtnActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            
            //display course_Credit DataTable
            DisplayCourse_Credit dis_cr_cdt = new DisplayCourse_Credit();
            dis_cr_cdt.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CourseCredit_BtnActionPerformed

    private void Enrollments_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enrollments_BtnActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            
            //display Enrollments DataTable
            DisplayEnrollments dis_enrol = new DisplayEnrollments();
            dis_enrol.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(TableList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Enrollments_BtnActionPerformed

    private void Grades_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grades_BtnActionPerformed
        DisplayGrades dis_grd = new DisplayGrades();
        dis_grd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Grades_BtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //open DashBoard
        DashBoard db = new DashBoard();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        //open pereq table DisplayPreReq
        
         DisplayPreReq dp = new DisplayPreReq();
        dp.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        //open log
         DisplayLogs dl = new DisplayLogs();
        dl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Classes_Btn;
    private javax.swing.JButton CourseCredit_Btn;
    private javax.swing.JButton Course_Btn;
    private javax.swing.JButton Enrollments_Btn;
    private javax.swing.JButton Grades_Btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
